name: beauty_solution_seller_app
description: "A new Flutter project."

publish_to: "solution"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # ****** Localization *******
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0 # for localization in app 


  # ****** UI *******
  cupertino_icons: ^1.0.8  # for cupertino icons
  flutter_spinkit: ^5.2.1  # for loading spinners in app
  flutter_screenutil: ^5.9.3  # for responsive ui
  country_picker: ^2.0.26
  
  


 


 
  # ****** Network *******
  dio: ^5.5.0    # for network requests and api calls
 

  # ****** caching *******
  #hive_flutter: ^1.1.0 # for caching data in cache storage

  # ! Services

  # ****** State Management *******
  flutter_bloc: ^8.1.6  # for State Management
  freezed_annotation: ^2.4.2 # for generating imitable freezed classes and methods 
 




  # ****** DataBase And Files *******
  path_provider: ^2.1.3
  file_picker: ^8.0.6 # for file picker for images and files

  # ****** Maps *******
  #flutter_osm_plugin: ^1.1.0 # for open street maps
  open_street_map_search_and_pick: ^0.1.1
  geocoding: ^3.0.0



# Add permission handler for managing permissions
  permission_handler: ^11.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  # *To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/jsons/
    - assets/jsons/lang/

 #*To add fonts to your application, add a fonts section, like this:
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 200
